spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assignmentdb # your db host
    username: root # your userid
    password: admn1234  # your password
  jpa:
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop

logging:
  file:
    path: logs

import-path: ../../../tm_assessment/assessment/load_data/ # your path